### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by terzano** [nmrshll/gphotos-uploader-cli#36]
Running inside FreeBSD jail w/ Go version 1.11.4

```
 ./gphotos-uploader-cli
[INFO] Config file found. Loading...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7ac988]

goroutine 1 [running]:
github.com/zalando/go-keyring.Get(0x912495, 0x1c, 0xc000022700, 0x17, 0x6, 0x800cc54d8, 0x453990, 0x800cbbb00)
        /root/go/src/github.com/zalando/go-keyring/keyring.go:32 +0x28
github.com/nmrshll/gphotos-uploader-cli/datastore/tokenstore.RetrieveToken(0xc000022700, 0x17, 0x1000000000008, 0x18, 0x18)
        /root/go/src/github.com/nmrshll/gphotos-uploader-cli/datastore/tokenstore/tokenstore.go:37 +0x4e
github.com/nmrshll/gphotos-uploader-cli/upload.authenticate(0xc00014e120, 0xc00014e120, 0xc0000c9be0, 0x40db78)
        /root/go/src/github.com/nmrshll/gphotos-uploader-cli/upload/folderUploadJob.go:61 +0x51
github.com/nmrshll/gphotos-uploader-cli/upload.NewFolderUploadJob(0xc000154180, 0xc000152060, 0xc000020ea0)
        /root/go/src/github.com/nmrshll/gphotos-uploader-cli/upload/folderUploadJob.go:38 +0x62
main.startUploader(0xc000130780, 0xcd04c0, 0x0, 0x0)
        /root/go/src/github.com/nmrshll/gphotos-uploader-cli/cmd/gphotos-uploader-cli/main.go:37 +0x20a
github.com/spf13/cobra.(*Command).execute(0xc000130780, 0xc00001e1b0, 0x0, 0x0, 0xc000130780, 0xc00001e1b0)
        /root/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000130780, 0x2, 0x0, 0xc000130c80)
        /root/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc000130780, 0xc0000cdf68, 0x1)
        /root/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /root/go/src/github.com/nmrshll/gphotos-uploader-cli/cmd/gphotos-uploader-cli/main.go:76 +0x16a

```

**Comment by nmrshll** [comment]
At first look it seems that either we use the lib `go-keyring` wrong or it simply doesn't have support for FreeBSD

We'll need to check what we might be doing wrong first, else we can always ask the `go-keyring` community

**Comment by pacoorozco** [comment]
Solved
